name: Lighthouse
on: [push]
jobs:
  mobile:
    name: Lighthouse mobile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: npm install, build
        run: |
          pnpm install
          pnpm run build
      - name: lighthouse mobile audit
        run: pnpm run lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  desktop:
    name: Lighthouse desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: npm install, build
        run: |
          pnpm install
          pnpm run build
      - name: lighthouse desktop audit
        run: pnpm run lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}